apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redline-api
  labels:
    app: redline-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redline-api
  template:
    metadata:
      labels:
        app: redline-api
    spec:
      containers:
        - name: redline-api
          image: ghcr.io/sombriks/redline/redline-api:2024.07.20-f69008c
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PG_CONNECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map-redline-api
                  key: PG_CONNECTION_URL
            - name: EMAIL_API_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map-redline-api
                  key: EMAIL_API_URL
            - name: EMAIL_API_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config-map-redline-api
                  key: EMAIL_API_USERNAME
            - name: EMAIL_API_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config-map-redline-api
                  key: EMAIL_API_PASSWORD
