apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-redline-api
spec:
  ingressClassName: traefik
  rules:
    - host: api.redline.sombriks.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-redline-api
                port:
                  number: 3000

