apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redline-app
  labels:
    app: redline-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redline-app
  template:
    metadata:
      labels:
        app: redline-app
    spec:
      containers:
        - name: redline-app
          image: ghcr.io/sombriks/redline/redline-app:2024.04.07-942b9f1
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
