### List modelocategoria

GET {{url}}/modelocategoria
Content-Type: application/json

### List tipo conta

GET {{url}}/tipo_conta
Content-Type: application/json

### List tipo movimentacao

GET {{url}}/tipo_movimentacao
Content-Type: application/json

### List tipo recorrencia

GET {{url}}/tipo_recorrencia
Content-Type: application/json

### Attempt to admin login

POST {{url}}/login
Content-Type: application/json

{
  "email": "adm@meudinheiro.cc",
  "senha": "e1e2e3e4"
}

> {% client.global.set("token", response.body.json.token) %}

### Create new user

POST {{url}}/signup
Content-Type: application/json

{
  "nome": "teste 1",
  "email": "teste@teste.com",
  "senha": "e1e2e3e4"
}


> {% client.global.set("lastUserId", response.body.json.id) %}

### Update user

PUT {{url}}/user/{{lastUserId}}
Content-Type: application/json
Authorization: `Bearer {{token}}`

{
  "nome": "teste 2",
  "email": "teste@teste.com",
  "senha": "e2e3e4e5"
}

### List users

### Check user categories

### Remove user

### Create user and

### Add an account

### Add an entry to the account

### Modify an entry - add a category

### Remove entry

### Add planning

### Update planning

### List plannings

### Remove planning

### Create new category

### Add entry to new category
