# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI - backend

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: service-node-koa

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web-app-vue/package-lock.json
    - name: Run tests
      run: |
        npm ci
        npm run build --if-present
        npm run test:service:coverage
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}:service-node-koa"
        file: infrastructure/Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/sombriks/redline-api:latest
#          ghcr.io/sombriks/redline-api:${{env.TAG}}

